"""add stitch projects and contributions

Revision ID: 01dd7d0aff18
Revises: f8822fdf8c89
Create Date: 2026-10-01 11:13:39.440108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dd7d0aff18'
down_revision: Union[str, None] = 'f8822fdf8c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stitch_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('moderator_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interest_slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allow_contributions', sa.Boolean(), nullable=False),
    sa.Column('stitched_video_url', sa.String(length=500), nullable=True),
    sa.Column('stitch_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stitch_projects_interest_slug'), 'stitch_projects', ['interest_slug'], unique=False)
    op.create_index(op.f('ix_stitch_projects_moderator_id'), 'stitch_projects', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_stitch_projects_status'), 'stitch_projects', ['status'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('contributor_id', sa.String(length=36), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['stitch_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_contributor_id'), 'contributions', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_contributions_project_id'), 'contributions', ['project_id'], unique=False)
    op.create_index(op.f('ix_contributions_status'), 'contributions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_status'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_project_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_contributor_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_stitch_projects_status'), table_name='stitch_projects')
    op.drop_index(op.f('ix_stitch_projects_moderator_id'), table_name='stitch_projects')
    op.drop_index(op.f('ix_stitch_projects_interest_slug'), table_name='stitch_projects')
    op.drop_table('stitch_projects')
    # ### end Alembic commands ###
