"""add follows, blocks, audience, is_private

Revision ID: 393b634d3d17
Revises: 9499b70b1ba3
Create Date: 2026-10-04 23:19:07.813225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393b634d3d17'
down_revision: Union[str, None] = '9499b70b1ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blocker_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    op.create_index(op.f('ix_blocks_blocked_id'), 'blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_blocks_blocker_id'), 'blocks', ['blocker_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follower_id', sa.String(length=36), nullable=False),
    sa.Column('following_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)

    # --- CHANGED: added server_default so existing rows get a value ---
    op.add_column(
        'posts',
        sa.Column('audience', sa.String(length=20), nullable=False, server_default='public')
    )
    op.create_index(op.f('ix_posts_audience'), 'posts', ['audience'], unique=False)
    op.create_index('ix_posts_audience_created', 'posts', ['audience', 'created_at'], unique=False)

    # --- CHANGED: added server_default so existing rows get a value ---
    op.add_column(
        'users',
        sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###
    
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_private')
    op.drop_index('ix_posts_audience_created', table_name='posts')
    op.drop_index(op.f('ix_posts_audience'), table_name='posts')
    op.drop_column('posts', 'audience')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_blocks_blocker_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocked_id'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
