"""add is_moderator to users

Revision ID: 3cfcf89bbeaa
Revises: e4d928097c7e
Create Date: 2026-10-01 21:00:56.151798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfcf89bbeaa'
down_revision: Union[str, None] = 'e4d928097c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'is_moderator',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    # ### end Alembic commands ###
