"""add media moderation fields to posts

Revision ID: 5e74c7641e38
Revises: 393b634d3d17
Create Date: 2026-10-07 23:33:20.366425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e74c7641e38'
down_revision: Union[str, None] = '393b634d3d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column(
            'media_moderation_status',
            sa.String(length=20),
            nullable=False,
            server_default='pending',
        )
        )
    op.add_column('posts', sa.Column('media_moderation_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_posts_media_moderation_status'), 'posts', ['media_moderation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_media_moderation_status'), table_name='posts')
    op.drop_column('posts', 'media_moderation_reason')
    op.drop_column('posts', 'media_moderation_status')
    # ### end Alembic commands ###
