"""add engagement_signals table

Revision ID: 5f99ff8dfd79
Revises: 107f74f46822
Create Date: 2026-10-10 13:01:58.694915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f99ff8dfd79'
down_revision: Union[str, None] = '107f74f46822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_signals_post_id'), 'engagement_signals', ['post_id'], unique=True)
    op.create_index(op.f('ix_engagement_signals_score'), 'engagement_signals', ['score'], unique=False)
    op.create_index(op.f('ix_engagement_signals_verdict'), 'engagement_signals', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engagement_signals_verdict'), table_name='engagement_signals')
    op.drop_index(op.f('ix_engagement_signals_score'), table_name='engagement_signals')
    op.drop_index(op.f('ix_engagement_signals_post_id'), table_name='engagement_signals')
    op.drop_table('engagement_signals')
    # ### end Alembic commands ###
