"""add moderation_logs table

Revision ID: 6ab434aab02c
Revises: 98703e3fc70c
Create Date: 2026-10-01 13:33:35.730119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab434aab02c'
down_revision: Union[str, None] = '98703e3fc70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_action'), 'moderation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_moderation_logs_actor_id'), 'moderation_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_target_id'), 'moderation_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_target_type'), 'moderation_logs', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_logs_target_type'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_target_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_actor_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_action'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    # ### end Alembic commands ###
