"""add screen sessions and user screen time fields

Revision ID: 88f8b43119b3
Revises: 5f99ff8dfd79
Create Date: 2026-10-10 13:41:05.222707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f8b43119b3'
down_revision: Union[str, None] = '5f99ff8dfd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'screen_sessions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_screen_sessions_user_id'), 'screen_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_screen_sessions_started_at'), 'screen_sessions', ['started_at'], unique=False)

    op.add_column(
        'users',
        sa.Column('daily_screen_time_limit_minutes', sa.Integer(), nullable=False, server_default='60')
    )
    op.add_column(
        'users',
        sa.Column('break_reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'break_reminders_enabled')
    op.drop_column('users', 'daily_screen_time_limit_minutes')
    op.drop_index(op.f('ix_screen_sessions_user_id'), table_name='screen_sessions')
    op.drop_index(op.f('ix_screen_sessions_started_at'), table_name='screen_sessions')
    op.drop_table('screen_sessions')
    # ### end Alembic commands ###
