"""add last_dob_change_at to users

Revision ID: 8a5569a675aa
Revises: f47f158fef38
Create Date: 2026-10-04 11:29:47.223331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5569a675aa'
down_revision: Union[str, None] = 'f47f158fef38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_dob_change_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_dob_change_at')
    # ### end Alembic commands ###
