"""add community_id to posts

Revision ID: 9499b70b1ba3
Revises: 8402ae70b974
Create Date: 2026-10-04 13:54:23.337481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9499b70b1ba3'
down_revision: Union[str, None] = '8402ae70b974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('community_id', sa.String(length=36), nullable=True))
    op.create_index('ix_posts_community_created', 'posts', ['community_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_community_id'), 'posts', ['community_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'communities', ['community_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_community_id'), table_name='posts')
    op.drop_index('ix_posts_community_created', table_name='posts')
    op.drop_column('posts', 'community_id')
    # ### end Alembic commands ###
