"""add posts table

Revision ID: f8822fdf8c89
Revises: 929e476abab0
Create Date: 2026-10-01 09:48:00.400133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8822fdf8c89'
down_revision: Union[str, None] = '929e476abab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('interest_slug', sa.String(length=50), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_label_shown', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_interest_created', 'posts', ['interest_slug', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_interest_slug'), 'posts', ['interest_slug'], unique=False)
    op.create_index(op.f('ix_posts_moderation_status'), 'posts', ['moderation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_moderation_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_interest_slug'), table_name='posts')
    op.drop_index('ix_posts_interest_created', table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
